# ANA 680 HW 1  Fairbairn
# Naive Bayes

In [1]:
#linear regression
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
import pickle

## load the processed dataset

In [2]:
file_path= 'C:/David/ANA 680 Machine Learning Deployment/Data/StudentsPerformance.csv'
df=pd.read_csv(file_path)

In [3]:
df.shape

(1000, 8)

In [4]:

df.head(3)

gender race/ethnicity parental level of education     lunch  \
0  female        group B           bachelor's degree  standard   
1  female        group C                some college  standard   
2  female        group B             master's degree  standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93

## Naive Bayes

In [5]:
X = df[['math score','reading score','writing score']].values
Y = df[['race/ethnicity']].values

## Split the dataset for training and test

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=7)

## Instantiate the model with default parameters

In [7]:
model = GaussianNB()

### fit the model with data

In [8]:
model.fit(X_train, y_train.ravel())

GaussianNB()

### Create Predictions

In [9]:
y_pred = model.predict(X_test)

## Print the model score

In [10]:
score = model.score(X_test, y_test)
print(score)

0.352


## Print the confusion Matrix

In [11]:
cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)

[[ 0  5 16  6  0]
 [ 0  2 25 14  1]
 [ 0  5 44 18  9]
 [ 0  3 33 31  5]
 [ 0  1  6 15 11]]


In [12]:
# Open a file and use dump()
with open('file_midterm.pkl','wb') as file:
    #create a new file 
    pickle.dump(model,file)